### PR TITLE
stop a11y from running in install

### PR DESCRIPTION
**Pull request by lc512k**
This was causing pa11y to run on install
@keirog @leggsimon

### CODE REVIEW

**Comment by leggsimon** [comment]
How did this ever work with any other apps???

**Comment by lc512k** [comment]
It was a recent update to n-makefile. I guess other apps didn't have the latest build-tools yet so we hadn't noticed until it broke today in next-static. Nice catch, btw 🙌

**Comment by leafrogers** [comment]
Oops, thanks for fixing! Any idea why it was being triggered?

**Comment by lc512k** [comment]
My makefile knowledge is limited, so I don't really know why @keirog :| I tried commenting it out and things just worked. I did wonder if this would break some of your work in components, though?

**Comment by leafrogers** [comment]
Weird `¯\_(ツ)_/¯`! Hopefully we’ll find out at some point. It doesn’t affect the component work though, so no bother. I just added the alias because I’d seen people (including me, initially) writing `ally` instead of `a11y`. The benefit doesn’t outweigh the time to fix it though ✌️

**Pull request merged**
