### PR TITLE
Help target

### PR DESCRIPTION
**Pull request by sjparkinson**
An initial pass at adding a help target.

There's a comment convention for it to pickup targets to list:

```make
target-name: ## Target description.
```

Should look something like the following:

```
$ make help
usage: make [target] ...

targets:
aws-policy-test        Test
clean                  Clean this git repository.
install                Setup this repository.
deploy                 Deploy this repository.
verify                 Verify this repository.
assets                 Build the static assets.
assets-production      Build the static assets for production.
build                  Build this repository.
build-production       Build this repository for production.
watch                  Watch for static asset changes.
update-tools           Update this Makefile.
help                   Show this help message.
```

Seems to work as expected, but only done a little bit of manual Q&A.

### CODE REVIEW

**Comment by sjparkinson** [comment]
Looks like this'd break the hack described in https://github.com/Financial-Times/n-makefile/blob/master/CONTRIBUTION.md#common-rule-conventions.

**Comment by matthew-andrews** [comment]
yeah, quite a few apps override these commands so i'd gently suggest not to use this approach.  could you put the command name in the comments and get it out from there instead?

e.g.

```
update-tools: ## update-tools: Update this Makefile.
```

Might make the code to parse the makefiles simpler too.

**Comment by sjparkinson** [comment]
Yep that was the alternative!

Will make some time for it this week.

**Comment by sjparkinson** [comment]
Couldn't simplify the parsing really, but open to suggestions.

**Comment by sjparkinson** [comment]
Ready for another review, now including docs and and better grep.

**Pull request merged**
