### PR TITLE
Allow uglification as an option

### PR DESCRIPTION
**Pull request by matthew-andrews**
fyi @ironsidevsquincy @phamann you can now set `n-makefile.json`'s `assets.compress` property to compress them with uglifyjs (or not do that to continue to not compress them).

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
:-1: 

I tried this, and I'm pretty sure using the Uglify plugin removes comments in css, i.e. will remove autoprefixer comments (https://github.com/Financial-Times/n-card/blob/master/_mixins.scss#L7), i.e. this will break the layout in certain browsers

Unless someone can confirm this is not the case, or knows how to fix it, I wouldn't allow this as an option

**Comment by matthew-andrews** [comment]
I'll have a go at making a reduced test case.

As far as I could tell though it should only be applied to JS files.  If it's not I'll try to make it.

**Comment by ironsidevsquincy** [comment]
Problem is, webpack converts css _into_ JS, as far as it's concerned it is just JS

**Comment by matthew-andrews** [comment]
we fixed it ^_^

**Pull request merged**
