### PR TITLE
Don't automatically run the .env target.

### PR DESCRIPTION
**Pull request by adambraimbridge**
Re: https://github.com/Financial-Times/n-makefile/issues/128

@sjparkinson @bjfletcher @wheresrhys @lc512k

### CODE REVIEW

**Comment by adambraimbridge** [comment]
Re: https://github.com/Financial-Times/n-makefile/issues/128

**Comment by sjparkinson** [comment]
Solves point 2, _but_ I now have to run `make install && make .env` to set up locally.

Worth updating the readme, or output a notice.

**Comment by adambraimbridge** [comment]
Update: I've tested this by manually updating n-Makefile here: https://github.com/Financial-Times/next-mission-control/commit/839029d2c7d5a183854722a5f5ef503e7f090305

It is now passing the build in CircleCI because `make install` no longer invokes the `.env` target. CircleCI can run `make install` with impunity. 

Todo: Update `make install` so that, when appropriate, it prompts developers to execute `make .env`.

**Comment by adambraimbridge** [comment]
Thinking about this even more ... why don't we just do the same thing in the developer environment that we do for CircleCI? That is, forget about the .env file entirely and rely on a dev equivalent of the "Exporting env vars from project settings" step?

image

Obviously it'd take lots of work and it's not top priority, but <shrugs> might be a cool approach in the long run.

**Comment by adambraimbridge** [comment]
Update: I spoke too soon. We're getting errors but they're ignored by CircleCI ...

image

**Comment by adambraimbridge** [comment]
Update: It looks like the additional invocations of the `.env` target were being called via `sinclude .env` at the top of Makefile. According to [this documentation](https://www.gnu.org/software/make/manual/html_node/Include.html), `sinclude` is an alias of `-include`. The minus sign prefix makes it ignore errors — which explains why the errors were not failing the previous CircleCI build. 

I've removed the `sinclude .env` line; but left the proceeding line, which reads .env if it exists and exports the contents to environment variables, because it's probably useful in`make run` and `make test`. (I might be wrong — maybe n-express takes care of that ...)
 
Oh, and I added an appropriate notice to `install`. And updated the README.

image

### Good news
It's looking much better now in CircleCI.
image

**Pull request merged**
