### PR TITLE
first stab at self-updating dotfiles

### PR DESCRIPTION
**Pull request by wheresrhys**
Haven't tested if this actually works, but does the process reflect what we discussed? @matthew-andrews

### CODE REVIEW

**Comment by wheresrhys** [comment]
also see https://github.com/Financial-Times/n-makefile/pull/48

**Comment by matthew-andrews** [comment]
cool, i will take it for a spin

**Comment by wheresrhys** [comment]
what's your workflow for working with nMakefile?

**Comment by matthew-andrews** [comment]
suboptimal

**Comment by matthew-andrews** [comment]
[copy+paste]

**Pull request closed without merging**
