### PR TITLE
Gitignore "*.env*"

### PR DESCRIPTION
**Pull request by adambraimbridge**
It looks like it wants to work ... 

image

... but it also seems to be running `make .env` _even if I only call `make` by itself_ :scream: 

image

### CODE REVIEW

**Comment by lc512k** [comment]
@adambraimbridge iirc, running `make` on its own is equivalent to running `make x` where `x` is the first target in the makefile. ~~So that's actually probably just running `make test`? (from looking at https://github.com/Financial-Times/next-mission-control/blob/master/Makefile)~~

`make` is running `make install` and that is triggering `.env`

LGTM

**Comment by sjparkinson** [comment]
@adambraimbridge if `.env` is required in `.gitignore` for this Makefile to work, why not append it rather than error?

**Comment by adambraimbridge** [comment]
@sjparkinson Good question — In this case, the .gitignore file did actually have `.env` in it, but not `*.env*`. I guess appending it would be a bit messy.

I might take this opportunity to _comment_ (not a complaint or a criticism!) that there's a lot going on in Makefile that seems rather esoteric. I frankly have no clue of the reasoning behind some of the business logic. 

For example, I can guess as to why the CIRCLECI environment variable must *not* be set. Or, for that matter, exactly _why_  package.json's name property must be "correct" — and what actually _makes_ it correct. But those guesses could easily be wrong.

So how could it be improved? Well, apparently you _can_ add comments to makefiles ... I think a little commenting would go a long way here. And many more clear error messages :)

**Comment by bjfletcher** [comment]
Very nice! Thanks Adam! :)

**Pull request merged**
